config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "beasts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  resources :bookings, only: [:index]
  resources :beasts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:edit, :update]
  patch "bookings/:id/pay", to: "bookings#pay", as: "booking_pay"
  patch "bookings/:id/cancel", to: "bookings#cancel", as: "booking_cancel"


  get "/dashboard", to: "users#dashboard"

  namespace :owner do
    resources :beasts, only: [:index]
    resources :bookings, only: [:index] do
      member do
        patch :accept
        patch :decline
        patch :cancel
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/beast.rb
class Beast < ApplicationRecord
  has_many :users, through: :bookings
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  belongs_to :owner, class_name: "User"

  CATEGORY = ["Aquatique", "Volante", "Terrestre", "Sous-terraine"]

  validates :name, presence: true
  validates :description, presence: true
  validates :price_per_day, presence: true
  # validates :owner_id, presence: true
  validates :category, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name,
                  against: [:name, :category],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :beast
  belongs_to :user
  validates :date_start, presence: true
  validates :date_end, presence: true
  # Le statut peut être : "created", "validated", "payed", "canceled"
  validates :status, inclusion: { in: %w[created validated modified payed canceled] }

  # validates :date_end_date_start_date

  # private

  # def date_end_date_start_date
  #   return if end_date.blank? || start_date.blank?

  #   if end_date < start_date
  #     errors.add(:end_date, "must be after the start date")
  #   end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :beasts, through: :bookings
  has_many :bookings, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  # demande l'authentification systematique
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    beasts_path
  end
end

app/controllers/beasts_controller.rb
class BeastsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @beasts = Beast.all
    if params[:query].present?
      @beasts = Beast.search_by_name(params[:query])
    end
  end

  def new
    @beast = Beast.new
  end

  def create
    @beast = Beast.new(beast_params)
    @beast.owner = current_user
    if @beast.save
      redirect_to beast_path(@beast)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @beast = Beast.find(params[:id])
    @owner = @beast.owner == current_user
    @booking = Booking.new
  end

  def edit
    @beast = Beast.find(params[:id])
  end

  def update
    @beast = Beast.find(params[:id])
    if @beast.update(beast_params)
      redirect_to beast_path(@beast)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @beast = Beast.find(params[:id])
    @beast.delete
    redirect_to beasts_path, status: :see_other
  end

  private

  def beast_params
    params.require(:beast).permit(:name, :description, :price_per_day, :category, :speed, photos: [])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user: current_user)
  end

  def new
    @booking = Booking.new
    @beast = Beast.find(params[:beast_id])
  end

  def create
    @user = current_user
    @beast = Beast.find(params[:beast_id])

    # Crée une nouvelle instance de Booking avec les bons paramètres
    @booking = Booking.new(booking_params)

    # Associe les relations à l'objet Booking
    @booking.user = @user
    @booking.beast = @beast

    # Attribut le statut "created" à la nouvelle reservation
    @booking.status = "created"

    # Tente de sauvegarder et gère les résultats
    if @booking.save
      redirect_to beast_path(@beast), notice: "Votre reservation à bien été prise en compte"
    else
      render "beasts/show", status: :unprocessable_entity, notice: "Choisissez vos dates de location !"
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.status = "modified"
    if @booking.update(booking_params)
      redirect_to bookings_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def cancel
    # Récupére la reservation
    @booking = Booking.find(params[:id])
    # Modifie la valeur associée à status en "canceled"
    @booking.update_attribute(:status, "canceled")
    redirect_to bookings_path, status: :see_other
  end

  def pay
    # Récupére la reservation
    @booking = Booking.find(params[:id])
    # Modifie la valeur associée à status en "payed"
    @booking.update_attribute(:status, "payed")
    redirect_to bookings_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:date_start, :date_end, :beast_id, :user_id)
  end
end

app/controllers/owner/beasts_controller.rb
class Owner::BeastsController < ApplicationController
  def index
    @beasts = Beast.where(owner: current_user)
  end

  def show
    @booking = Booking.find(params[:id])
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  def index
    # TODO: récupérer les locations
    @owner_beasts = Beast.where(owner: current_user)
    @bookings = Booking.where(beast: @owner_beasts)
  end

  def accept
    # Récupére la reservation
    @booking = Booking.find(params[:id])
    # Modifie la valeur associée à status en "validated"
    @booking.update_attribute(:status, "validated")
    redirect_to owner_bookings_path, status: :see_other
  end

  def decline
    # Récupére la reservation
    @booking = Booking.find(params[:id])
    # Modifie la valeur associée à status en "canceled"
    @booking.update_attribute(:status, "canceled")
    redirect_to owner_bookings_path, status: :see_other
  end

  def cancel
    # Récupére la reservation
    @booking = Booking.find(params[:id])
    # Modifie la valeur associée à status en "canceled"
    @booking.update_attribute(:status, "canceled")
    redirect_to owner_bookings_path, status: :see_other
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @is_owner = Beast.where(owner: current_user).present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beasts/_beasts_form.html.erb
  <%= simple_form_for @beast do |f| %>
    <%= f.input :name, label: "Nom"%>
    <%= f.input :description, as: :text%>
    <%# Enlever as: :float, remplacer par :text%>
    <%= f.input :price_per_day, as: :float, label: "Prix à la journée"%>
    <%= f.input :photos, as: :file, input_html: { multiple: true }%>
    <%= f.input :category, collection: Beast::CATEGORY, default: Beast::CATEGORY, label: "Catégorie"%>
    <%# Enlever as: :float, remplacer par :text%>
    <%= f.input :speed, as: :float, label: "Vitesse"%>
    <%= f.submit "Valider", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/beasts/_list_beasts.html.erb
<div class="row">
  <% if !@beasts.nil?%>
  <%@beasts.each do |beast|%>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3">
      <%= link_to beast_path(beast), class: "text-decoration-none" do%>
        <div class="card m-1 d-flex flex-column justify-content-between" style="height: 500px;">
          <%unless beast.photos.empty?%>
              <%= image_tag beast.photos[0], class: "card-img-top", style: "height: 200px; object-fit: cover;"%>
          <%else%>
            <img class="card-img-top" style="height: 200px; object-fit: cover;" src=<%= beast.image%> alt="Card image cap">
          <%end%>
          <div class="card-body">
            <h5 class="card-title">
              <%= beast.name%>
            </h5>
            <p class="card-text, text-truncate"><%= beast.description%></p>
            <h6 class="card-subtitle mb-2 text-muted">
              <i class="fa-solid fa-tag"></i>
              <%= beast.category%>
            </h6>
            <h6 class="card-subtitle mb-2 text-muted">
              <i class="fa-solid fa-gauge"></i>
              <%= beast.speed%> km/h
            </h6>
            <h6 class="card-subtitle mb-2 text-muted">
              <i class="fa-solid fa-sack-dollar"></i>
              <%= beast.price_per_day%> €
            </h6>
          </div>
          <div class="card-footer d-flex justify-content-center">
          <% if !user_signed_in? || (user_signed_in? && beast.owner_id != current_user.id) %>
            <%= link_to beast_path(beast), class: "btn btn-success" do %>
              <i class="fa-solid fa-calendar-plus"></i> Réserver !
            <% end %>
          <% end %>
            <% if user_signed_in? %>
              <%if beast.owner_id == current_user.id %>
                <%= link_to beast_path(beast),
                data: {turbo_method: :delete, turbo_confirm: "Êtes-vous sûr?"},
                class:"btn btn-danger" do %>
                  <i class="fa-solid fa-trash"></i> Supprimer
                <% end %>
              <% end %>
            <%end%>
          </div>
        </div>
      <%end%>
    </div>
  <%end%>
  <%else%>
  <%= "pas de b" %>
  <% end %>
</div>

app/views/beasts/edit.html.erb
<div class="container">
  <% current_user.email if user_signed_in? %>
  <h1><%= "MODIFIER MA CREATURE" %></h1>
 <%= render "beasts/beasts_form", beast: @beast%>
</div>

app/views/beasts/index.html.erb
<%= render partial: 'beasts/list_beasts', beasts: @beasts %>

app/views/beasts/new.html.erb
<div class="container">
  <% current_user.email if user_signed_in? %>
  <h1>NOUVELLE CREATURE</h1>
 <%= render "beasts/beasts_form", beast: @beast %>
 </div>

app/views/beasts/show.html.erb
<div class="container">
  <div class="row"> <!-- Utilisation d'une rangée Bootstrap -->
    <div class="col-md-6 mb-3"> <!-- Colonne pour les images (maintenant à gauche) -->
      <%# Affichage des images %>
      <div class="image-gallery mb-3">
        <%unless @beast.photos.empty?%>
          <%= image_tag @beast.photos[0], class: "img-fluid col-md-12 rounded mb-3", alt: "Image de la créature" %>
        <%else%>
          <%= image_tag @beast.image, class: "img-fluid col-md-12 rounded mb-3", alt: "Image de la créature" %>
        <%end%>
        <%# Affichage des petites images %>
        <div class="row thumbnail-gallery">
          <%# <% 3.times do %>
            <%unless @beast.photos.empty? || @beast.photos.count <= 1 %>
              <%# si il n'y a que deux photo : une seule petite photo %>
              <% if @beast.photos.count <= 2 %>
              <div class="col-4 mb-3">
                <%= image_tag @beast.photos[1], class: "img-fluid rounded thumbnail", alt: "Miniature de la créature" %>
              </div>
              <%# si il n'y a que 3 photos : deux petites photos %>
              <% elsif @beast.photos.count <= 3 %>
              <div class="col-4 mb-3">
                <%= image_tag @beast.photos[1], class: "img-fluid rounded thumbnail", alt: "Miniature de la créature" %>
              </div>
              <div class="col-4 mb-3">
                <%= image_tag @beast.photos[2], class: "img-fluid rounded thumbnail", alt: "Miniature de la créature" %>
              </div>
              <%# s'il y a 4 photos : trois petites photos %>
              <% elsif @beast.photos.count <= 4 %>
              <div class="col-4 mb-3">
                <%= image_tag @beast.photos[1], class: "img-fluid rounded thumbnail", alt: "Miniature de la créature" %>
              </div>
              <div class="col-4 mb-3">
                <%= image_tag @beast.photos[2], class: "img-fluid rounded thumbnail", alt: "Miniature de la créature" %>
              </div>
              <div class="col-4 mb-3">
                <%= image_tag @beast.photos[3], class: "img-fluid rounded thumbnail", alt: "Miniature de la créature" %>
              </div>
              <% end %>
              <%# <%else%>
              <%# <div class="col-4 mb-3"> %>
                <%# <%= image_tag @beast.image, class: "img-fluid rounded thumbnail", alt: "Miniature de la créature" %>
              <%# </div> %>
            <%end%>
          <%# <% end %>
        </div>
      </div>

    </div>
    <div class="col-md-6"> <!-- Colonne pour le texte (maintenant à droite) -->
      <h1><%= @beast.name %></h1>

      <h3>
      <i class="fa-solid fa-tag"></i>
      <%= @beast.category %>
      </h3>

      <h5>
      <i class="fa-solid fa-sack-dollar"></i>
      <%= @beast.price_per_day %> €
      </h5>

      <h5>
      <i class="fa-solid fa-gauge"></i>
      <%= @beast.speed %> km/h
      </h5>

     <p><%= @beast.description %></p>
    <div class="mt-3"> <!-- Boutons -->
      <% if @owner %>
        <%= link_to edit_beast_path(@beast), class: "btn btn-primary me-2" do %>
        <i class="fa-solid fa-pen-to-square"></i> Modifier
        <% end %>
        <%= link_to beast_path(@beast),
        data: { turbo_method: :delete, turbo_confirm: "Vous êtes sûr ?" },
        class: "btn btn-danger" do %>
        <i class="fa-solid fa-trash"></i> Supprimer
        <% end %>
      <% end %>
      <%# Affichage conditionnel du formulaire de reservation %>
      <div class = "mt-3">
        <% unless @beast.owner_id == current_user.id %>
          <%= render "bookings/form", beast:@beast, booking:@booking %>
        <% end %>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<%= simple_form_for [@beast, @booking] do |f| %>
  <%= f.input :date_start,
            label: "Date de début",
            as: :string,
            minDate: "today",
            input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :date_end,
            label: "Date de fin",
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
  <%= f.submit "Réserver !", class: "btn btn-success", data: {turbo_method: :post, turbo_confirm: "Vous confirmez votre réservation ?"}%>
<% end %>

app/views/bookings/edit.html.erb
<h1>Modifier ma reservation</h1>
<%= simple_form_for [@booking] do |f| %>
  <%= f.input :date_start,
            label: "Date de début",
            as: :string,
            minDate: "today",
            input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :date_end,
            label: "Date de fin",
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
  <%= f.submit "Confirmer la réservation", class: "btn btn-primary", data: {turbo_method: :post, turbo_confirm: "Vous confirmez votre réservation ?"}%>
<% end %>

app/views/bookings/index.html.erb
<%= render "shared/dashboard-page-title", title: "Mes réservations" %>
<%if @bookings.empty?%>
  <p>Aucune réservation</p>
<%else%>
  <ul class="list-group">
    <% @bookings.each do |booking|%>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div>
          <div class="fw-bold">
            <%=booking.beast.name%>
          </div>
          <p>Du <%=booking.date_start%> au <%=booking.date_end%></p>
          <p><%=calcul =(booking.date_end - booking.date_start).to_i * booking.beast.price_per_day%> €</p>
        </div>
        <div class="d-flex flex-column justify-content-between">
          <%= render "shared/timeline", status: booking.status %>
          <%# indique le status de la reservation %>
          <div class="mt-3">
            <% if booking.status == "created" || booking.status == "modified" %>
              <p>En attente de validation</p>
            <% elsif booking.status == "validated" %>
              <p>En attente de paiement</p>
            <% elsif booking.status == "payed" %>
              <p>Reservation confirmée</p>
            <% elsif booking.status == "canceled" %>
              <p>Reservation annulée</p>
            <% end %>
          </div>
        </div>
        <div class="d-flex">
          <%# si le status est créé ou validé, on peut modifier (pas si c'est payé, modifié ou annulé) %>
          <div class="mx-1">
            <% if booking.status == "created" || booking.status == "validated" %>
              <%= link_to "Modifier", edit_booking_path(booking.id), class: "btn btn-primary" %>
            <% end %>
          </div>
          <div class="mx-1">
            <%# si le status est tout sauf annulé, on voit le bouton annuler %>
            <% unless booking.status == "canceled" %>
              <%= link_to "Annuler", booking_cancel_path(booking.id), data: {turbo_method: :patch}, class: "btn btn-outline-danger"%>
            <%end%>
          </div>
          <div class="mx-1">
            <%# Ajouter le path quand la method "pay" et sa route seront créés %>
            <% if booking.status == "validated" %>
              <%= link_to "Payer", booking_pay_path(booking.id), data: {turbo_method: :patch, turbo_confirm: "Voulez vous payer #{calcul =(booking.date_end - booking.date_start).to_i * booking.beast.price_per_day}€ ??" }, class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </li>
    <%end%>
  </ul>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Beastly Riders" %></title>
    <link rel="icon" type="image/png" href="<%= image_path("star.png") %>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>
  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
    <% if controller_name == 'beasts' && action_name == 'index' %>
      <%= render "shared/banner" %>
    <%end%>
    <div class="container container-principal my-3">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/owner/beasts/index.html.erb
<%= render "shared/dashboard-page-title", title: "Mes créatures" %>
<%# TODO: Créer une partials de card %>
<%if @beasts.nil?%>
<%else%>
<%= render partial: 'beasts/list_beasts'%>
<% end %>

app/views/owner/bookings/index.html.erb
<%= render "shared/dashboard-page-title", title: "Mes demandes de locations" %>
<%if @bookings.empty?%>
  <p>Aucune demande de location</p>
<%else%>
  <ul class="list-group">
    <% @bookings.each do |booking|%>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div>
          <div class="fw-bold">
            <%=booking.beast.name%>
          </div>
          <p>Du <%=booking.date_start%> au <%=booking.date_end%></p>
          <p><%=booking.beast.price_per_day%> €</p>
          <p>
            <%= booking.user.email%>
          </p>
        </div>
        <div class="d-flex flex-column justify-content-between">
          <%= render "shared/timeline", status: booking.status %>
          <%# indique le status de la reservation %>
          <div class="mt-3">
            <% if booking.status == "created" || booking.status == "modified" %>
              <p>En attente de validation</p>
            <% elsif booking.status == "validated" %>
              <p>En attente de paiement</p>
            <% elsif booking.status == "payed" %>
              <p>Reservation confirmée</p>
            <% elsif booking.status == "canceled" %>
              <p>Reservation annulée</p>
            <% end %>
          </div>
        </div>
        <div class="d-flex">
          <%# si le status est créé ou validé, on peut modifier (pas si c'est payé, modifié ou annulé) %>
          <div class="mx-1">
            <% if booking.status == "created" || booking.status == "modified" %>
              <%= link_to "Accepter", accept_owner_booking_path(booking.id), data: {turbo_method: :patch}, class: "btn btn-primary" %>
            <% end %>
          </div>
          <%# si le status est créé ou modifié, on peut refuser %>
          <div class="mx-1">
            <% if booking.status == "created" || booking.status == "modified" %>
              <%= link_to "Refuser", decline_owner_booking_path(booking.id), data: {turbo_method: :patch}, class: "btn btn-primary" %>
            <% end %>
          </div>
          <%# si le status n'est pas cancel ou payed, le owner peut annuler %>
          <div class="mx-1">
            <% unless booking.status == "canceled" || booking.status == "payed" %>
              <%= link_to "Annuler la reservation", cancel_owner_booking_path(booking.id), data: {turbo_method: :patch}, class: "btn btn-outline-danger" %>
            <% end %>
          </div>
        </div>
      </li>
    <%end%>
  </ul>
<%end%>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="container d-flex justify-content-center align-items-center">
    <div>
      <div class="mb-5">
        <h1 class="fs-1">Beastly Riders</h1>
        <h6 class="card-subtitle text-white">Éveillez le rider en vous ...</h6>
      </div>
      <%# Search bar %>
      <div>
        <%= form_with url: beasts_path, method: :get, class: "d-flex gap-1" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Rechercher..."%>
          <%= button_tag type: "submit", name: "", class: "btn btn-primary" do %>
            <i class="fa-solid fa-magnifying-glass"></i>
          <%end%>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/shared/_dashboard-page-title.html.erb
<div class="mb-3">
  <div class="mb-3">
    <%= link_to dashboard_path, class: "text-decoration-none" do%>
      <i class="fa-solid fa-arrow-left"></i> retour
    <%end%>
  </div>
  <h1 class="fs-4">
    <%= title%>
  </h1>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="py-3 my-4">
  <ul class="nav justify-content-center border-bottom pb-2 mb-2">
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Accueil</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Tarifs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Nous contacter</a></li>
  </ul>
  <p class="text-center text-body-secondary">© 2024 Beastly Riders 🦄, Inc</p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light navbar-beast">
  <%# Image avec le logo pour revenir à la home %>
  <div class= "d-flex">
    <%= link_to root_path, class:"d-flex align-items-baseline m-2" do %>
      <div>
        <%= image_tag "logo.png" %>
      </div>
      <div>
        <h5 class="logo m-2">Beastly Riders</h5>
      </div>
    <% end %>
  </div>
  <div class="d-flex mr-4">
    <%= link_to "Proposer la location de ma monture", new_beast_path, class: "btn purple-btn p-2 m-3" %>
    <%# Si pas authentifié, bouton Sign up %>
    <%if user_signed_in?%>
      <%= link_to "Tableau de bord", dashboard_path, class: "nav-link active m-3 p-2"%>
    <%else%>
      <%= link_to "Se connecter", new_user_session_path, class: "nav-link active m-3 p-2"%>
    <%end%>
  </div>
</nav>

app/views/shared/_timeline.html.erb
<%# Timeline %>
<div class="d-flex">
  <div class="timeline-<%= status == 'payed' || status == 'validated' ? 'green' : 'orange' %>">
    <div class="container-timeline-green">
    </div>
  </div>
  <div class="timeline-<%= status == 'payed' ? 'green' : 'orange'%>">
    <div class="container-timeline-<%= status == 'payed' || status == 'validated' ? 'green' : 'orange'%>">
    </div>
  </div>
  <div class="timeline-green-last">
    <div class="container-timeline-<%= status == 'payed' ? 'green' : 'orange'%>">
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="container mt-4">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <div>
      <h1 class="mb-2">Tableau de bord de <%= current_user.email %> </h1>
      <h3 class="text-muted">
      </h3>
    </div>
    <div>
      <% if user_signed_in? %>
        <%= link_to destroy_user_session_path,
                    class: "btn btn-outline-danger",
                    data: { turbo_method: :delete,
                            turbo_confirm: "Vous confirmez la déconnexion ?" } do %>
          <i class="fas fa-sign-out-alt"></i> Déconnexion
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="d-flex flex-column align-items-center">
    <%= link_to bookings_path, class: "btn btn-primary btn-lg mb-3 w-50" do %>
      <i class="fas fa-calendar-alt me-2"></i> Mes Réservations
    <% end %>

    <% if @is_owner %>
      <%= link_to owner_beasts_path, class: "btn btn-primary btn-lg mb-3 w-50" do %>
        <i class="fas fa-dragon me-2"></i> Mes créatures
      <% end %>

      <%= link_to owner_bookings_path, class: "btn btn-primary btn-lg mb-3 w-50" do %>
        <i class="fas fa-book me-2"></i> Mes créatures en location
      <% end %>
    <% end %>
  </div>
</div>